### ISSUE TITLE
Addititional packages

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#11]
For debugging and configuration purposes, we should at least add man-db and / or man-pages.

**Comment by kontextwechsel** [comment]
Fixed with commit [Add man-db and man-pages to base system](https://github.com/kontextwechsel/arch-linux-installation/commit/e78f1a98368da31e78f25000272eaf0740f6908d) and [Remove deprecated man package](https://github.com/kontextwechsel/arch-linux-installation/commit/4f3636787b21a9dfb784b8d254b5aebeb32fc66e).
