### ISSUE TITLE
Re-enter password mechanism

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#12]
To prevent typos in the first place, we should consider to add a mechanism to ask the user to re-enter their passwords during installation. 
Otherwise you have to repeat the whole installation process.

**Comment by kontextwechsel** [comment]
Fixed with commit [Use dedicated password for LUKS disk encryption](https://github.com/kontextwechsel/arch-linux-installation/commit/2a5b0518ad8932931fc4e713620b25cc8ca3b11f) and [Make dedicated disk encryption password optional](https://github.com/kontextwechsel/arch-linux-installation/commit/e70a19dbedf58f0f9b284db8d0be520e4878631c).
