### ISSUE TITLE
Keep initial wifi configuration in wpa_supplication 

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#9]
In order to fetch and install the arch-linux-installation routines, one has to establish an Internet connection in the first place. 

Wifi users need to select their SSID and enter a PSK. These steps have to be done again within the installation. The idea is to let wifi users decide to keep the configuration and automatically add the already provided parameters to the wpa_supplicant.<interface>.conf afterwards. 

An implementation is on the way.

**Comment by ghost** [comment]
The initial approach to extract the credentials from either iwd or wpa is not very feasible, thus should be avoided. The code complexity would increase and I'm not sure if a user would benefit from it that much.

The PR therefore asks for the SSID and password and will be set in wpa-config.

**Comment by kontextwechsel** [comment]
Fixed with commit [Add Wi-Fi credentials to wpa_supplicant configuration](https://github.com/kontextwechsel/arch-linux-installation/commit/10150ddecbf361e301d826edefc4e5ae2b7c05ca) and [Make default Wi-Fi optional and not fail if password is wrong](https://github.com/kontextwechsel/arch-linux-installation/commit/51934fb6b1ec1c9f44d12d2c3c5135c8b5526426).
